test failure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,6 +41,12 @@ jobs:
         name: test-results
         path: test/TestResults/
 
+    - name: Fail pipeline if tests failed
+      if: steps.run-tests.outcome == 'failure'
+      run: |
+        echo "Tests failed. Failing pipeline."
+        exit 1
+
     - name: Upload compiler artifact
       uses: actions/upload-artifact@v3
       with:
